all:
	gcc -o concurrency4_1 concurrency4_1.c -mrdrnd -lpthread
	gcc -o concurrency4_2 concurrency4_2.c -mrdrnd -lpthread

part1:
	gcc -o concurrency4_1 concurrency4_1.c -mrdrnd -lpthread

part2:
	gcc -o concurrency4_2 concurrency4_2.c -mrdrnd -lpthread

clean:
	rm -f concurrency4_2
	rm -f concurrency4_1
