all:
	gcc -o concurrency3_1 concurrency3_1.c -mrdrnd -lpthread
	gcc -o concurrency3_2 concurrency3_2.c -mdrnd -lpthread

part1:
	gcc -o concurrency3_1 concurrency3_1.c -mrdrnd -lpthread

part2:
	gcc -o concurrency3_2 concurrency3_1.c -mrdrnd -lpthread

clean:
	rm -f concurrency3_2
	rm -f concurrency3_1
